version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.19-browsers
    steps:
      # - browser-tools/install-browser-tools
      - checkout

      - run:
          name: "list version"
          command: |
            php --version
            google-chrome --version

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update

      - run:
          name: "Install php sqlite ext"
          command: |
            sudo apt-get install php8.1-sqlite3

      - run:
          name: "Create environment file"
          command: |
            mv .env.testing .env

      # download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      # prepare the database
      - run:
          name: "Create database and run migration"
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing

      # run phpunit tests
      - run:
          name: "Run Tests"
          command: php artisan test
